GH #42 - Update enmasse support

diff --git a/vagrant/zato-3.1/provisioning/setup.yml b/vagrant/zato-3.1/provisioning/setup.yml
--- a/vagrant/zato-3.1/provisioning/setup.yml
+++ b/vagrant/zato-3.1/provisioning/setup.yml
@@ -99,42 +99,88 @@
     url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/quickstart/zato_start_load_balancer
     dest: /opt/zato/zato_start_load_balancer
     mode: 0755
+    owner: zato
+    group: zato
 
 - name: Zato | Download /opt/zato/zato_start_scheduler
   get_url:
     url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/quickstart/zato_start_scheduler
     dest: /opt/zato/zato_start_scheduler
     mode: 0755
+    owner: zato
+    group: zato
 
 - name: Zato | Download /opt/zato/zato_start_server1
   get_url:
     url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/quickstart/zato_start_server1
     dest: /opt/zato/zato_start_server1
     mode: 0755
+    owner: zato
+    group: zato
 
 - name: Zato | Download /opt/zato/zato_start_server2
   get_url:
     url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/quickstart/zato_start_server2
     dest: /opt/zato/zato_start_server2
     mode: 0755
+    owner: zato
+    group: zato
 
 - name: Zato | Download /opt/zato/zato_start_web_admin
   get_url:
     url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/quickstart/zato_start_web_admin
     dest: /opt/zato/zato_start_web_admin
     mode: 0755
+    owner: zato
+    group: zato
 
 - name: Zato | Download /opt/zato/hotdeploy-utility.sh
   get_url:
     url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/cloud/hotdeploy-utility.sh
     dest: /opt/zato/hotdeploy-utility.sh
     mode: 0755
+    owner: zato
+    group: zato
 
-- name: Zato | Download /opt/zato/enmasse-utility.sh
-  get_url:
-    url: https://raw.githubusercontent.com/zatosource/zato-build/master/docker/cloud/enmasse-utility.sh
+- name: Zato | Enable enmasse
+  copy:
+    content: |
+      #!/bin/bash
+      source /opt/zato-env.sh
+
+      /usr/local/bin/dockerize -wait tcp://localhost:17010 -timeout 10m || exit 1
+
+      # add a new wait time
+      sleep 5
+
+      cd /opt/zato/env/qs-1 || exit 1
+      [[ -z ${ZATO_SERVER_PATH} ]] && ZATO_SERVER_PATH="/opt/zato/env/qs-1/server1"
+      if [[ ! -f ${ZATO_SERVER_PATH}/config/repo/server.conf ]]; then
+          echo "Zato server configuration not found at ${ZATO_SERVER_PATH}"
+          exit 1
+      fi
+
+      if [[ -n "$(echo "${ZATO_ENMASSE_FILE}"|grep -Eo '(http|https)://[^/"]+')" ]];then
+          echo "Downloading enmasse file from ${ZATO_ENMASSE_FILE}"
+          TMPFILE="$(mktemp -d)"
+          ZATO_ENMASSE_FILE_NAME=$(basename ${ZATO_ENMASSE_FILE})
+          curl "${ZATO_ENMASSE_FILE}" > ${TMPFILE}/${ZATO_ENMASSE_FILE_NAME}
+          ZATO_ENMASSE_FILE="${TMPFILE}/${ZATO_ENMASSE_FILE_NAME}"
+      fi
+
+      set -x # enable show commands
+      if [[ -f ${ZATO_ENMASSE_FILE} ]]; then
+          /opt/zato/current/bin/zato enmasse ${ZATO_SERVER_PATH} --input ${ZATO_ENMASSE_FILE} --import --replace-odb-objects
+      else
+          echo "enmasse file ${ZATO_ENMASSE_FILE} not found"
+          exit 1
+      fi
+      set +x # disable show commands
     dest: /opt/zato/enmasse-utility.sh
-    mode: 0755
+    mode: '0755'
+    owner: zato
+    group: zato
+  notify: restart supervisor
 
 - name: Zato | Create quickstart directory
   file: path=/opt/zato/env/qs-1/ owner=zato group=zato
